[Service] Fix pip requirements.txt (#59)
**Description:**

Fix `requirements.txt` for development setup.

**Changes Made:**

- Use IPEX-LLM stable version `2.1.0` instead of nightly pre-release.
Installation may fail because nightly pre-releases become unavailable
after certain period of time.
```
ERROR: Could not find a version that satisfies the requirement bigdl-core-xe-21==2.5.0b20240705 (from versions: 2.1.0b2, 2.5.0b1, 2.5.0b2, 2.5.0b20240515, 2.5.0, 2.6.0b20240830, 2.6.0b20240831, 2.6.0b20240901, 2.6.0b20240902, 2.6.0b20240903, 2.6.0b20240904, 2.6.0b20240905, 2.6.0b20240906, 2.6.0b20240907, 2.6.0b20240908, 2.6.0b20240909, 2.6.0b20240910, 2.6.0b20240911, 2.6.0b20240912, 2.6.0b20240913, 2.6.0b20240917, 2.6.0b20240918, 2.6.0b20240919)
ERROR: No matching distribution found for bigdl-core-xe-21==2.5.0b20240705
```

- Fix dependency conflicts between `langchain, langchain-community,
langchain_core`.
```
ERROR: Cannot install -r service\requirements-ultra.txt (line 11) and langchain==0.2.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested langchain==0.2.2
    langchain-community 0.2.9 depends on langchain<0.3.0 and >=0.2.9

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict


ERROR: Cannot install -r service\requirements-ultra.txt (line 10) and langchain_core==0.2.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested langchain_core==0.2.4
    langchain-community 0.2.9 depends on langchain-core<0.3.0 and >=0.2.22

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict
```

- Uplift IPEX version to `2.1.40`
- Update README

**Testing Done:**

Phi-3-mini works with a fresh environment setup on Intel(R) Core(TM)
Ultra 5 125H system.

![image](https://github.com/user-attachments/assets/337946e1-407f-4d41-acf0-87ae8df14741)

**Checklist:**

- [x] I have tested the changes locally.
- [x] I have self-reviewed the code changes.
- [x] I have updated the documentation, if necessary.